### ISSUE TITLE
Unable to build (Windows 64x)

### ISSUE THREAD

**Issue by crNewton** [ERBO-Engineering/cmake-stm32#1]
Thanks for this repo, and the [Medium article.](https://medium.com/@erbo-engineering/using-vs-code-for-embedded-stm32-development-14405ed4ac82) 
I gave it a try but was unable to build successfully:

I first tried with cygwin64 (since I had that installed already):
_"st-flash", "make", "cmake", "openocd", "arm-none-eabi-gcc"_ are available in my path.
building resulted in the error: _'nosys.specs': No such file or directory_
(I don't understand where this error comes from because the CMakeLists.txt has 'STM32::NoSys')

I then removed cygwin from my path env. variables, installed make etc. (following the medium article), and rebooted. 
Now _"st-flash", "make", "cmake", "openocd", "arm-none-eabi-gcc"_ are available in my path (without using cygwin).
Building results in the error: 'fatal error C1189: #error:  Unknown compiler', full output:

```
C:\projectDir\cmake-stm32\build>cmake --build .
Microsoft (R) Build Engine version 16.11.2+f32259642 for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

cl : command line warning D9002: ignoring unknown option '--sysroot="/usr/arm-none-eabi"' [C:\projectDir\cmake-stm32\build\cmake-stm32.vcx
proj]
  main.c
cl : command line warning D9002: ignoring unknown option '-mthumb' [C:\projectDir\cmake-stm32\build\cmake-stm32.vcxproj]
cl : command line warning D9002: ignoring unknown option '-ffunction-sections' [C:\projectDir\cmake-stm32\build\cmake-stm32.vcxproj]       
cl : command line warning D9002: ignoring unknown option '-fdata-sections' [C:\projectDir\cmake-stm32\build\cmake-stm32.vcxproj]
cl : command line warning D9002: ignoring unknown option '-mcpu=cortex-m4' [C:\projectDir\cmake-stm32\build\cmake-stm32.vcxproj]
cl : command line warning D9002: ignoring unknown option '-mfpu=fpv4-sp-d16' [C:\projectDir\cmake-stm32\build\cmake-stm32.vcxproj]
cl : command line warning D9002: ignoring unknown option '-mfloat-abi=hard' [C:\projectDir\cmake-stm32\build\cmake-stm32.vcxproj]
C:\projectDir\cmake-stm32\BSP\Drivers\CMSIS\Include\cmsis_compiler.h(261,1): fatal error C1189: #error:  Unknown compiler. [C:\projectDir\cmake-stm32\build\cmake-stm32.vcxproj]
  system_stm32f4xx.c
C:\projectDir\cmake-stm32\BSP\Drivers\CMSIS\Include\cmsis_compiler.h(261,1): fatal error C1189: #error:  Unknown compiler. [C:\projectDir\cmake-stm32\build\cmake-stm32.vcxproj]
  stm32f4xx_hal_gpio.c
C:\projectDir\cmake-stm32\BSP\Drivers\CMSIS\Include\cmsis_compiler.h(261,1): fatal error C1189: #error:  Unknown compiler. [C:\projectDir\cmake-stm32\build\cmake-stm32.vcxproj]
  stm32f4xx_hal.c
C:\projectDir\cmake-stm32\BSP\Drivers\CMSIS\Include\cmsis_compiler.h(261,1): fatal error C1189: #error:  Unknown compiler. [C:\projectDir\cmake-stm32\build\cmake-stm32.vcxproj]
  Generating Code...
```

Any idea what I have setup wrong on my Windows64x system?

**Comment by ERBO-Engineering** [comment]
Hey @crNewton thanks for reading and trying out the repository.

We just tried it on Windows ourselves, and you are right, windows requires a bit more configuration, it seems.

Although we could not fully replicate your issue, we did see some resemblance in our results.
On our side, we discovered that CMake grabs the wrong "build system generator." in our case it grabbed nMake, and it seems that in your case it grabs some Microsoft build engine.

Could you try out the following

1. Remove your build folder
2. Recreate your build folder
3. Go into the build folder and run the following command `cmake .. -G "MinGW Makefiles"`
4. If everything went okay, you should now have a .hex or .bin file you can flash onto your target,

If this works, we will update the documentation 👍

**Comment by crNewton** [comment]
Thanks! That fixed it!

**Comment by ERBO-Engineering** [comment]
That's great to hear, if you have any further suggestions let us know.

We will close this issue now, good luck with your project!
